[package]
name = "zaino-state"
description = "A mempool and chain-fetching service built on top of zebra's ReadStateService and TrustedChainSync."
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
version = { workspace = true }

[dependencies]
zaino-fetch = { path = "../zaino-fetch" }
zaino-proto = { path = "../zaino-proto" }

# Zebra
zebra-chain = { workspace = true }
zebra-state = { workspace = true }
zebra-rpc = { workspace = true }

# Miscellaneous Workspace
tokio = { workspace = true, features = ["full"] }
thiserror = { workspace = true }
tower = { workspace = true, features = ["buffer", "util"] }
async-trait = { workspace = true }
chrono = { workspace = true }
indexmap = { workspace = true }
url = { workspace = true }
hex = { workspace = true, features = ["serde"] }
tokio-stream = { workspace = true }
futures = { workspace = true }
tonic = { workspace = true }
http = { workspace = true }
lazy-regex = { workspace = true }
dashmap = { workspace = true }
lmdb = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["preserve_order"] }
jsonrpc-core = { workspace = true }
prost = { workspace = true }

[dev-dependencies]
zaino-testutils = { path = "../zaino-testutils" }
zingo-infra-services = { workspace = true }

# ZingoLib
zingolib = { workspace = true }

[build-dependencies]
whoami = { workspace = true }
